"""add paystack_reference to orders

Revision ID: 093f7ebf7480
Revises: 3eb8c276c848
Create Date: 2026-04-02 12:44:54.480709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093f7ebf7480'
down_revision = '3eb8c276c848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_paystack_reference_key', 'orders', type_='unique')
    op.create_index(op.f('ix_orders_paystack_reference'), 'orders', ['paystack_reference'], unique=True)
    op.drop_column('orders', 'paystack_transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paystack_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_paystack_reference'), table_name='orders')
    op.create_unique_constraint('orders_paystack_reference_key', 'orders', ['paystack_reference'])
    # ### end Alembic commands ###