"""add embedding column to products

Revision ID: 3e35390e3b56
Revises: 093f7ebf7480
Create Date: 2026-04-07 08:48:40.693955

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '3e35390e3b56'
down_revision = '093f7ebf7480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding')
    # ### end Alembic commands ###