"""product and review tables

Revision ID: 3eb8c276c848
Revises: f59f94f470c8
Create Date: 2026-03-31 10:09:11.121241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb8c276c848'
down_revision = 'f59f94f470c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###