"""add password reset fields

Revision ID: f59f94f470c8
Revises: b88d4e3fd5e6
Create Date: 2026-03-27 10:55:39.859538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59f94f470c8'
down_revision = 'b88d4e3fd5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###